apps/web/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from . import views, api

app_name = 'web'
url_views = [
    path('home', views.home, name='home'),
    path('contact-us', TemplateView.as_view(template_name="web/pages/contact-us.html"), name='contact-us'),
    path('faq', TemplateView.as_view(template_name="web/pages/contact-us.html"), name='faq'),

    path('patients', views.patient_list, name='patients'),

    path('therapy', views.therapy, name='therapy'),
    path('therapy/session/<token>/c/<c_token>', views.therapy_client_site, name='therapy_client_site'),
    path('therapy/session/<token>/c/<c_token>/confirmation', views.therapy_client_confirm, name='therapy_client_confirm'),

    path('accounts/settings', views.account_settings, name='account_settings'),
    path('accounts/settings/deleting', views.account_settings_delete, name='account_settings_deleting'),
    path('accounts/settings/passwrod', views.account_settings, name='account_settings_passchange'),
    path('accounts/settings/profile', views.account_settings, name='account_settings_profilechange'),

    # Stripe
    path('accounts/subscription', include('apps.subscriptions.urls')),
    path('accounts/subscription/success', views.account_subscription_success, name='account_subscription_success'),
    path('accounts/subscription/canceled', views.account_subscription_canceled, name='account_subscription_canceled'),

    path('terms-and-conditions', TemplateView.as_view(template_name="web/pages/terms-and-conditions.html"), name='terms'),
    path('404', TemplateView.as_view(template_name='404.html'), name='404'),
    path('500', TemplateView.as_view(template_name='500.html'), name='500')
]

url_api = [
    path('api/patients', api.patients, name="api_patients"),
    path('api/patients/<patient_id>', api.patient, name="api_patient"),
    path('api/email/send', api.sending_email_to_patient, name='api_send_email'),
]

urlpatterns = url_views + url_api

memory_remedy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.documentation import include_docs_urls, get_schemajs_view

schemajs_view = get_schemajs_view(title="API")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include('apps.users.urls')),
    path('subscriptions/', include('apps.subscriptions.urls')),
    path('', include('pages.urls')),
    path('', include('apps.web.urls')),
    # path('pegasus/', include('pegasus.apps.examples.urls')),
    # path('celery-progress/', include('celery_progress.urls')),
    # API docs
    # these are needed for schema.js
    # path('docs/', include_docs_urls(title='API Docs')),
    # path('schemajs/', schemajs_view, name='api_schemajs'),
    # djstripe urls - for webhooks
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

templates/web/pages/therapy/client.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
  <title>Memory Rmedy</title>
</head>
<body>

<div class="columns p-4">
  <div class="column is-fullwidth">
    <div id="dotBox" style="height: 100%; width: 100%; min-height: 35rem; position: relative; background: rgb(255, 255, 255);">
      <div id="dot" style="height: 30px; width: 30px; border-radius: 50%; background: rgb(0, 0, 0); position: absolute; left: 0px; top: 0px;"></div>
    </div>
  </div>
</div>

<script src="//code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="/static/web/js/client.js"></script>
<script>
  setPatient(`{{ patient }}`);
</script>
</body>
</html>

templates/web/pages/therapy/client_confirm.html
{% extends "web/layout_simple.html" %}
{% load static %}

{% block body %}
  <section class="hero is-fullheight">
    <div class="hero-body">
      <div class="container">
        <div class="columns is-centered">
          <div class="column is-12-tablet is-6-desktop is-6-widescreen has-text-centered">
            <img src="/static/web/images/logo-blue.svg" alt="">
          </div>
          <div class="column is-12-tablet is-6-desktop is-6-widescreen has-text-centered box p-5">
            <form action="{% url 'web:therapy_client_confirm' token=token c_token=c_token %}" method="POST">
              {% csrf_token %}
              <div class="field is-horizontal">
                <div class="field-label">
                  <label class="label">First Name</label>
                </div>
                <div class="field-body">
                  <div class="field">
                    <div class="control has-text-left">
                      {{ patient.first_name }}
                    </div>
                  </div>
                </div>
              </div>

              <div class="field is-horizontal">
                <div class="field-label">
                  <label class="label">Last Name</label>
                </div>
                <div class="field-body">
                  <div class="field">
                    <div class="control has-text-left">
                      {{ patient.last_name }}
                    </div>
                  </div>
                </div>
              </div>

              <div class="field is-horizontal">
                <div class="field-label">
                  <label class="label">Email</label>
                </div>
                <div class="field-body">
                  <div class="field">
                    <div class="control has-text-left">
                      {{ patient.email }}
                    </div>
                  </div>
                </div>
              </div>

              <div class="field is-horizontal">
                <div class="field-label">
                </div>
                <div class="field-body">
                  <div class="field">
                    <div class="control has-text-left">
                      <label for="" class="checkbox">
                        <input type="checkbox" required>
                        Accept <a href="{% url 'web:terms' %}" target="_blank">Terms & Condition*</a>
                      </label>
                    </div>
                  </div>
                </div>
              </div>

              <div class="field is-horizontal">
                <div class="field-label">
                  <!-- Left empty for spacing -->
                </div>
                <div class="field-body">
                  <div class="field">
                    <div class="control">
                      <button type="submit" class="button is-info is-fullwidth">
                        Go to URL
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/web/pages/therapy/index.html
{% extends "web/layout.html" %}
{% load static %}

{% block title %}
  <section class="section is-title-bar">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <ul>
            <li>Therapy</li>
          </ul>
        </div>
      </div>
      <div class="level-right">
        <div class="level-item">
        </div>
      </div>
    </div>
  </section>
{% endblock %}

{% block section %}
  <section class="section">
    <div class="columns">
      <div class="column is-4">
        <div class="card">
          <header class="card-header">
            <p class="card-header-title">Controls</p>
          </header>
          <div class="card-content">
            <form id="cpanel" class="control">
              <div class="field">
                <label class="label">Size</label>
                <div class="control">
                  <input id="size" class="slider is-fullwidth" step="1" min="40" max="200" type="range" value="30" />
                </div>
              </div>
              <div class="field">
                <label class="label">Speed</label>
                <div class="control">
                  <input id="speed" class="slider is-fullwidth" step="1" min="100" max="900" type="range" value="250" />
                </div>
              </div>
              <div class="field">
                <div class="control is-expanded">
                  <label class="checkbox">
                    <input type="checkbox" id="color" /> Color Changing Dot
                  </label>
                </div>
              </div>
              <div class="field">
                <label class="label">Dot Movement</label>
                <div class="control">
                  <div class="select is-fullwidth">
                    <select id="mode">
                      <option value="emdr-linear">Linear</option>
                      <option value="emdr-non-linear">8-Shape</option>
                      <option value="random">Random</option>
                      <option value="diamond">Diamond</option>
                      <option value="diagonal">Diagonal</option>
                      <option value="diagonal-flipped">Diagonal Flipped</option>
                    </select>
                  </div>
                </div>
              </div>
              <div class="field is-fullwidth">
                <label class="label">Background</label>
                <div class="control">
                  <div class="select is-fullwidth">
                    <select id="bg">
                      <option value="#fff">Light Background</option>
                      <option value="#333">Dark Background</option>
                      <option value="practice">Therapy Practice</option>
                      <option value="forrest">Forrest</option>
                      <option value="mountains">Mountains</option>
                      <option value="beach">Beach</option>
                      <option value="hospital">Hospital</option>
                      <option value="upload" disabled="">Upload Image (Pro)</option>
                    </select>
                  </div>
                </div>
              </div>
              <div class="field">
                <label class="label">Sound</label>
                <div class="control">
                  <div class="select is-fullwidth">
                    <select id="sound">
                      <option value="">No Sound</option>
                      <option value="/static/sounds/sound_1.mp3">Sound 1</option>
                      {#                      <option value="01-EMDR">Sound 1</option>#}
                      <option disabled="" value="PRO-05-EMDR">Sound 2 (Pro)</option>
                      <option disabled="" value="PRO-12-EMDR">Sound 3 (Pro)</option>
                      <option disabled="" value="PRO-14-EMDR">Sound 4 (Pro)</option>
                      <option disabled="" value="PRO-18-EMDR">Sound 5 (Pro)</option>
                    </select>
                  </div>
                </div>
              </div>
            </form>
            <br>
            <button id="runDot" class="button is-info">Start</button>
          </div>
        </div>
        <div class="card">
          <header class="card-header">
            <p class="card-header-title">Patients</p>
          </header>
          <div class="card-content">
            <form method="POST">
              {% csrf_token %}
              <div class="field has-addons">
                <div class="control" style="width: 100%">
                  <div class="select is-expanded is-fullwidth">
                    <select id="patient" name="patient" class="is-fullwidth">
                      <option value="" hidden {% if not selected_patient %} selected {% endif %}>
                        Select a patient
                      </option>
                      {% for patient in patients %}
                        <option value="{{ patient.id }}" {% if selected_patient == patient.id %} selected {% endif %}>
                          {{ patient.email }}
                        </option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <div class="control">
                  <button type="submit" class="button is-info" title="Refresh link">
                    <i class="fas fa-refresh"></i> Reload
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="card">
          <header class="card-header">
            <p class="card-header-title">What your client sees</p>
          </header>
          <div class="card-content">
            <div class="columns is-multiline">
              <div class="column is-fullwidth">
                <div id="dotBox" style="height: 100%; width: 100%; min-height: 31.15rem; position: relative; background: rgb(255, 255, 255);">
                  <div id="dot" style="height: 30px; width: 30px; border-radius: 50%; background: rgb(0,0,0); position: absolute; left: 0px; top: 0px;"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header">
            <p class="card-header-title">Guideline and Link</p>
          </div>
          <div class="card-content">
            <div style="padding: 0px 15px;">
              <ol class="has-text-grey-darker">
                <li class="py-1">
                  Start a video call with your client. Use any video call application tool.
                </li>
                <li class="py-1">
                  Ask you client to visit URL:
                  <br>
                  <div class="field has-addons">
                    <div class="control" style="width: 100%">
                      <input readonly value="{{ link }}" id="link" class="input" type="text" placeholder="Select a patient to get a link">
                    </div>
                    <div class="control">
                      <button id="sendBtn" class="button is-info">Send Link</button>
                    </div>
                  </div>
                </li>
                <li class="py-1">
                  When they are not on that page, they will see what is the screen above (full screen) and you can start the therapy
                </li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

{% block page_js %}
  <script src="/static/web/js/therapy.js"></script>
  <script>
    setPatient(`{{ selected_patient }}`);
    $(document).ready(function() {
      console.log("LOADED");
      $("#sendBtn").click(function() {
        console.log("CLICKED");
        const crf_token = $('[name="csrfmiddlewaretoken"]').val();
        const email = $("#patient :selected").text().trim();
        const link = $("#link").val();
        console.log(email, link);
        $.ajax({
          headers:{"X-CSRFToken": crf_token},
          type: "POST",
          url: `/api/email/send`,
          data: {
            email: email,
            link: link
          }
        }).done((res) => {
          $("#messages").append(`
            <li>
              <div class="is-info notification">
                <button class="delete"></button>
                An email has been sent
              </div>
            </li>
          `);
        }).fail((err) => {
          $("#messages").append(`
            <li>
              <div class="is-danger notification">
                <button class="delete"></button>
                Something went wrong.
              </div>
            </li>
          `);
        })

      });
    });
  </script>
{% endblock %}